import type { Epic, Workspace } from "./types"

export const workspaces: Workspace[] = [
  { id: "ws-1", name: "Beads Core" },
  { id: "ws-2", name: "Mobile App" },
  { id: "ws-3", name: "Marketing Site" },
]

export const epics: Epic[] = [
  {
    id: "EPIC-001",
    type: "epic",
    title: "User Authentication System",
    description: "Implement complete user authentication flow including login, signup, password reset, and session management.",
    status: "in_progress",
    priority: "high",
    assignee: "Sarah Chen",
    comments: [
      {
        id: "c1",
        author: "Sarah Chen",
        content: "Started working on the OAuth integration.",
        timestamp: new Date("2026-01-15T10:30:00"),
      },
      {
        id: "c2",
        author: "Mike Johnson",
        content: "Let me know if you need help with the database schema.",
        timestamp: new Date("2026-01-16T14:22:00"),
      },
    ],
    children: [
      {
        id: "BEAD-103",
        type: "bug",
        title: "Session timeout not working",
        description: "Users are staying logged in indefinitely even after the configured session timeout period has elapsed. This is a critical security issue that needs immediate attention.\n\n## Steps to Reproduce\n1. Log in to the application\n2. Wait for the session timeout period (currently set to 30 minutes)\n3. Observe that the user is still logged in\n\n## Expected Behavior\nUser should be automatically logged out after 30 minutes of inactivity and redirected to the login page.\n\n## Actual Behavior\nUser remains logged in indefinitely. The session cookie appears to be refreshing on every request regardless of activity.\n\n## Technical Notes\n- Session management is handled in `/lib/auth/session.ts`\n- The issue may be related to the sliding window implementation\n- Redis session store timeout might not be configured correctly",
        acceptanceCriteria: "## Definition of Done\n\n- [ ] User is automatically logged out after 30 minutes of **inactivity**\n- [ ] Active user actions (clicks, form submissions) reset the timeout\n- [ ] Passive requests (polling, health checks) do **not** reset the timeout\n- [ ] User sees a warning toast 5 minutes before session expires\n- [ ] On logout, user is redirected to `/login` with a `session_expired=true` query param\n\n## Test Cases\n1. Idle timeout test: Leave browser idle for 31 minutes, verify logout\n2. Active use test: Continuously interact for 45 minutes, verify session persists\n3. Background tab test: Open in background tab, verify timeout still applies\n\n## Security Requirements\n- Session tokens must be invalidated server-side on timeout\n- Redis TTL must match configured timeout value",
        createdAt: new Date("2026-01-15T08:00:00"),
        updatedAt: new Date("2026-01-17T16:45:00"),
        labels: ["security", "p0-blocker", "auth"],
        status: "open",
        priority: "critical",
        assignee: "Mike Johnson",
        comments: [
          {
            id: "c-103-1",
            author: "Beads AI",
            content: "I've analyzed the session management implementation and identified the root cause of this issue. The problem stems from the `touchSession` configuration in `/lib/auth/session.ts` being set to `true`, which causes the Redis session store to refresh the TTL on every single request, regardless of whether it's an authenticated action or passive polling.\n\nHere's what's happening technically:\n1. The session middleware intercepts all requests, including background health checks and API polling\n2. Each interception triggers `session.touch()` which resets the 30-minute expiry timer\n3. Since the dashboard polls for notifications every 30 seconds, the session effectively never expires\n\nRecommended fix: Modify the session configuration to only touch the session on explicit user actions (form submissions, navigation, etc.) rather than passive requests. This can be achieved by adding a request classification layer that distinguishes between active and passive requests.",
            timestamp: new Date("2026-01-17T09:15:00"),
          },
          {
            id: "c-103-2",
            author: "Beads AI",
            content: "I've generated a proposed implementation for the session timeout fix. The changes span three files and introduce a new request classification system:\n\n**Changes to `/lib/auth/session.ts`:**\n- Added `isActiveRequest()` helper that checks request method and path patterns\n- Modified `touchSession` to be a function that returns `true` only for active requests\n- Added new `lastActivityTime` field to session schema for accurate idle tracking\n\n**Changes to `/middleware.ts`:**\n- Integrated the request classifier before session handling\n- Added bypass logic for health check endpoints (`/api/health`, `/api/ping`)\n- Implemented proper idle timeout calculation using `lastActivityTime`\n\n**New file `/lib/auth/request-classifier.ts`:**\n- Defines patterns for active vs passive requests\n- Exports `classifyRequest()` function used by middleware\n\nEstimated impact: This change will correctly enforce the 30-minute idle timeout while maintaining session continuity during active use. I recommend adding integration tests to verify the timeout behavior before deploying to production.",
            timestamp: new Date("2026-01-17T11:30:00"),
          },
          {
            id: "c-103-3",
            author: "Beads AI",
            content: "Security audit dependency detected. I've cross-referenced this bead with the project timeline and identified that the Q1 Security Audit (scheduled for January 25th) has this issue listed as a blocker in the audit checklist under \"Session Management Controls.\"\n\nBased on the current sprint capacity and the complexity assessment of the proposed fix, here's a recommended action plan:\n\n**Priority Escalation:** Recommend elevating this from the current sprint backlog to immediate hotfix status.\n\n**Resource Allocation:** Mike Johnson has 6 hours of unallocated capacity today. The estimated implementation time for the proposed fix is 4-5 hours including code review.\n\n**Risk Assessment:** \n- Deployment risk: LOW (changes are isolated to auth middleware)\n- Regression risk: MEDIUM (recommend running full auth test suite)\n- Rollback plan: Feature flag the new behavior, can instant-revert if issues arise\n\n**Timeline:** If work begins now, PR can be ready for review by 3 PM, merged by 5 PM, and deployed to staging for overnight soak testing. Production deployment can happen tomorrow morning, giving 5 days of buffer before the security audit.",
            timestamp: new Date("2026-01-17T14:00:00"),
          },
          {
            id: "c-103-4",
            author: "Beads AI",
            content: "PR #1247 has been submitted and I've completed an automated code review. Here's my analysis:\n\n**Code Quality Assessment: PASSED**\n- All new functions have proper TypeScript types\n- Test coverage for new code: 94%\n- No detected security vulnerabilities\n- Follows established patterns in the codebase\n\n**Test Results:**\n- Unit tests: 47/47 passing\n- Integration tests: 12/12 passing\n- New session timeout test: PASSING (verified 30-minute expiry after idle period)\n\n**Performance Impact:**\n- Added ~2ms latency to request classification (acceptable)\n- No memory footprint increase detected\n- Redis operations unchanged\n\n**Deployment Checklist:**\n- [x] Database migrations: None required\n- [x] Environment variables: None required\n- [x] Feature flags: `SESSION_IDLE_TIMEOUT_ENABLED` added (default: true)\n- [x] Rollback procedure: Set feature flag to false\n- [x] Monitoring: Added new metric `session.idle_timeout_triggered`\n\nRecommendation: Approve for merge. All automated checks pass and the implementation aligns with the proposed solution. Ready for human review of business logic.",
            timestamp: new Date("2026-01-17T16:45:00"),
          },
        ],
        parentId: "EPIC-001",
      },
      {
        id: "BEAD-104",
        type: "feature",
        title: "Remember me functionality",
        description: "Add remember me checkbox to login",
        status: "open",
        priority: "low",
        assignee: "",
        comments: [],
        parentId: "EPIC-001",
      },
    ],
    childEpics: [
      {
        id: "EPIC-001A",
        type: "epic",
        title: "Login & Signup Flow",
        description: "Core login and signup functionality",
        status: "in_progress",
        priority: "high",
        assignee: "Sarah Chen",
        comments: [],
        parentId: "EPIC-001",
        children: [
          {
            id: "BEAD-101",
            type: "task",
            title: "Implement login form",
            description: "Create login form with email and password fields",
            status: "closed",
            priority: "high",
            assignee: "Sarah Chen",
            comments: [],
            parentId: "EPIC-001A",
          },
          {
            id: "BEAD-102",
            type: "task",
            title: "Create signup form",
            description: "Build signup form with validation",
            status: "closed",
            priority: "high",
            assignee: "Sarah Chen",
            comments: [],
            parentId: "EPIC-001A",
          },
          {
            id: "BEAD-106",
            type: "task",
            title: "Password validation rules",
            description: "Implement strong password requirements",
            status: "in_progress",
            priority: "medium",
            assignee: "Sarah Chen",
            comments: [],
            parentId: "EPIC-001A",
          },
        ],
        childEpics: [],
      },
      {
        id: "EPIC-001B",
        type: "epic",
        title: "OAuth Integration",
        description: "Third-party OAuth provider integration",
        status: "in_progress",
        priority: "medium",
        assignee: "Sarah Chen",
        comments: [],
        parentId: "EPIC-001",
        children: [
          {
            id: "BEAD-107",
            type: "task",
            title: "Google OAuth setup",
            description: "Integrate Google OAuth provider",
            status: "closed",
            priority: "high",
            assignee: "Sarah Chen",
            comments: [],
            parentId: "EPIC-001B",
          },
          {
            id: "BEAD-108",
            type: "task",
            title: "GitHub OAuth setup",
            description: "Integrate GitHub OAuth provider",
            status: "in_progress",
            priority: "medium",
            assignee: "Sarah Chen",
            comments: [],
            parentId: "EPIC-001B",
          },
          {
            id: "BEAD-109",
            type: "chore",
            title: "Update auth dependencies",
            description: "Update NextAuth to latest version",
            status: "closed",
            priority: "medium",
            assignee: "Sarah Chen",
            comments: [],
            parentId: "EPIC-001B",
          },
        ],
        childEpics: [
          {
            id: "EPIC-001B-1",
            type: "epic",
            title: "OAuth Error Handling",
            description: "Handle OAuth edge cases and errors",
            status: "open",
            priority: "medium",
            assignee: "Mike Johnson",
            comments: [],
            parentId: "EPIC-001B",
            children: [
              {
                id: "BEAD-110",
                type: "bug",
                title: "Token refresh failing",
                description: "OAuth tokens not refreshing properly",
                status: "open",
                priority: "high",
                assignee: "Mike Johnson",
                comments: [],
                parentId: "EPIC-001B-1",
              },
              {
                id: "BEAD-111",
                type: "task",
                title: "Add retry logic",
                description: "Implement retry for failed OAuth requests",
                status: "open",
                priority: "medium",
                assignee: "",
                comments: [],
                parentId: "EPIC-001B-1",
              },
            ],
            childEpics: [],
          },
        ],
      },
    ],
  },
  {
    id: "EPIC-002",
    type: "epic",
    title: "Dashboard Redesign",
    description: "Complete overhaul of the main dashboard with new analytics widgets and improved UX.",
    status: "open",
    priority: "medium",
    assignee: "Alex Rivera",
    comments: [
      {
        id: "c3",
        author: "Alex Rivera",
        content: "Waiting for design approval from the product team.",
        timestamp: new Date("2026-01-18T09:15:00"),
      },
    ],
    children: [
      {
        id: "BEAD-201",
        type: "task",
        title: "Create wireframes",
        description: "Design initial wireframes for new dashboard",
        status: "closed",
        priority: "high",
        assignee: "Alex Rivera",
        comments: [],
        parentId: "EPIC-002",
      },
      {
        id: "BEAD-202",
        type: "task",
        title: "Implement chart components",
        description: "Build reusable chart components",
        status: "closed",
        priority: "high",
        assignee: "Alex Rivera",
        comments: [],
        parentId: "EPIC-002",
      },
      {
        id: "BEAD-203",
        type: "feature",
        title: "Real-time data updates",
        description: "Add WebSocket support for live updates",
        status: "open",
        priority: "medium",
        assignee: "",
        comments: [],
        parentId: "EPIC-002",
      },
      {
        id: "BEAD-204",
        type: "task",
        title: "Responsive layout",
        description: "Ensure dashboard works on all screen sizes",
        status: "closed",
        priority: "high",
        assignee: "Alex Rivera",
        comments: [],
        parentId: "EPIC-002",
      },
      {
        id: "BEAD-205",
        type: "bug",
        title: "Chart tooltip overlap",
        description: "Tooltips are cut off on edge charts",
        status: "open",
        priority: "low",
        assignee: "",
        comments: [],
        parentId: "EPIC-002",
      },
      {
        id: "BEAD-206",
        type: "chore",
        title: "Optimize bundle size",
        description: "Reduce chart library bundle",
        status: "open",
        priority: "medium",
        assignee: "Mike Johnson",
        comments: [],
        parentId: "EPIC-002",
      },
      {
        id: "BEAD-207",
        type: "task",
        title: "Add export functionality",
        description: "Export dashboard data as CSV/PDF",
        status: "open",
        priority: "low",
        assignee: "",
        comments: [],
        parentId: "EPIC-002",
      },
      {
        id: "BEAD-208",
        type: "feature",
        title: "Custom widget positioning",
        description: "Allow users to drag and drop widgets",
        status: "open",
        priority: "medium",
        assignee: "",
        comments: [],
        parentId: "EPIC-002",
      },
      {
        id: "BEAD-209",
        type: "task",
        title: "Dark mode support",
        description: "Implement dark mode for dashboard",
        status: "closed",
        priority: "high",
        assignee: "Alex Rivera",
        comments: [],
        parentId: "EPIC-002",
      },
      {
        id: "BEAD-210",
        type: "bug",
        title: "Memory leak in chart updates",
        description: "Charts cause memory leak on rapid updates",
        status: "in_progress",
        priority: "high",
        assignee: "Mike Johnson",
        comments: [],
        parentId: "EPIC-002",
      },
    ],
  },
  {
    id: "EPIC-003",
    type: "epic",
    title: "API v2 Migration",
    description: "Migrate all endpoints from REST to GraphQL and implement new versioning strategy.",
    status: "in_progress",
    priority: "critical",
    assignee: "Mike Johnson",
    comments: [],
    children: [
      {
        id: "BEAD-301",
        type: "task",
        title: "Set up GraphQL server",
        description: "Configure Apollo Server with schema",
        status: "closed",
        priority: "critical",
        assignee: "Mike Johnson",
        comments: [],
        parentId: "EPIC-003",
      },
      {
        id: "BEAD-302",
        type: "task",
        title: "Migrate user endpoints",
        description: "Convert user REST endpoints to GraphQL",
        status: "closed",
        priority: "high",
        assignee: "Mike Johnson",
        comments: [],
        parentId: "EPIC-003",
      },
      {
        id: "BEAD-303",
        type: "task",
        title: "Migrate project endpoints",
        description: "Convert project REST endpoints to GraphQL",
        status: "in_progress",
        priority: "high",
        assignee: "Sarah Chen",
        comments: [],
        parentId: "EPIC-003",
      },
      {
        id: "BEAD-304",
        type: "chore",
        title: "Update API documentation",
        description: "Document all new GraphQL queries and mutations",
        status: "open",
        priority: "medium",
        assignee: "",
        comments: [],
        parentId: "EPIC-003",
      },
      {
        id: "BEAD-305",
        type: "bug",
        title: "N+1 query problem",
        description: "DataLoader not working correctly",
        status: "closed",
        priority: "critical",
        assignee: "Mike Johnson",
        comments: [],
        parentId: "EPIC-003",
      },
      {
        id: "BEAD-306",
        type: "feature",
        title: "Real-time subscriptions",
        description: "Add GraphQL subscriptions for live updates",
        status: "open",
        priority: "medium",
        assignee: "",
        comments: [],
        parentId: "EPIC-003",
      },
    ],
  },
  {
    id: "EPIC-004",
    type: "epic",
    title: "Performance Optimization",
    description: "Improve application performance across all metrics including LCP, FID, and CLS.",
    status: "closed",
    priority: "high",
    assignee: "Alex Rivera",
    comments: [
      {
        id: "c4",
        author: "Alex Rivera",
        content: "All performance targets have been met!",
        timestamp: new Date("2026-01-20T16:45:00"),
      },
    ],
    children: [
      {
        id: "BEAD-401",
        type: "task",
        title: "Implement lazy loading",
        description: "Add lazy loading for images and components",
        status: "closed",
        priority: "high",
        assignee: "Alex Rivera",
        comments: [],
        parentId: "EPIC-004",
      },
      {
        id: "BEAD-402",
        type: "task",
        title: "Optimize database queries",
        description: "Add indexes and optimize slow queries",
        status: "closed",
        priority: "critical",
        assignee: "Mike Johnson",
        comments: [],
        parentId: "EPIC-004",
      },
      {
        id: "BEAD-403",
        type: "chore",
        title: "Set up performance monitoring",
        description: "Integrate performance monitoring tools",
        status: "closed",
        priority: "medium",
        assignee: "Sarah Chen",
        comments: [],
        parentId: "EPIC-004",
      },
    ],
  },
]
